### ISSUE TITLE
Won't work if there's no demultiplexing step first

### ISSUE THREAD

**Issue by makostadima** [tercen/trimgalore_operator#1]
It is not working if there's no demultiplexing step before. It is always looking into the write folder and gives an error message, if the input data comes from the read folder (as it will be the case when the demultiplexing step isn't needed). 

Here's the workflow on dev that I used for testing: https://dev.tercen.com/test-team/w/d494453057f12c960ee36e7d765fdebc

What if the folder on the crosstab view contained the whole file path rather than just the name of the containing folder? In that case the operator could work with both read and write folders.

Even when I copied the FASTQ-containing folder into the write folder I got an error because the operator is expecting a specific folder as input. See [here](https://github.com/tercen/trimgalore_operator/blob/c8bbb4ba04f10ba7bd9bada7059b13b5975d2ef5/main.R#L9).

**Comment by fcadete** [comment]
Operator now looks for the specified file first in the write, then in the input folder. New version works in both workflows: https://dev.tercen.com/test-team/w/d494453057f12c960ee36e7d765fdebc and https://dev.tercen.com/test-team/w/d494453057f12c960ee36e7d7660d77c

Can change it so it expects the whole path, but then we also need to change the value returned by Tercen when an external folder is selected as input. Right now it returns just the folder name, not the full path.

For future issues please use https://github.com/tercen/trimgalore_docker_operator . The R and docker parts of the operator have been merged there.
